# -*- coding: utf-8 -*-
"""K-Means Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqSWqpEZ0Zlcbax3edfOfv2N6ncmjZ2b

**Import Libraries and data**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
# %matplotlib inline

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("Mall_Customers.csv")

df.head(10)

df.shape

df.dtypes

df.info()

df.describe()

df.duplicated().sum()

print(df.columns)

cust_df = df.drop(['CustomerID', 'Genre'], axis=1)

cust_df.head()

from sklearn.preprocessing import StandardScaler

X=StandardScaler()

scaled_df=X.fit_transform(cust_df)

scaled_df

k_means=KMeans(n_clusters=2)

k_means.fit(scaled_df)

k_means.labels_

k_means.inertia_

k_means=KMeans(n_clusters=3)
k_means.fit(scaled_df)
k_means.inertia_

k_means=KMeans(n_clusters=4)
k_means.fit(scaled_df)
k_means.inertia_

k_means=KMeans(n_clusters=5)
k_means.fit(scaled_df)
k_means.inertia_

k_means=KMeans(n_clusters=6)
k_means.fit(scaled_df)
k_means.inertia_

wss=[]

for i in range(1,11):
  KM=KMeans(n_clusters=i)
  KM.fit(scaled_df)
  wss.append(KM.inertia_)

wss

plt.plot(range(1,11),wss)

k_means=KMeans(n_clusters=5)
k_means.fit(scaled_df)
labels=k_means.labels_

df["Clus_kmeans"]=labels
df.head(5)

from sklearn.metrics import silhouette_samples,silhouette_score

silhouette_score(scaled_df,labels)

sil_width=silhouette_samples(scaled_df,labels)

df["sil_width"]=sil_width
df.head(5)

silhouette_samples(scaled_df,labels).min()

df.to_csv('km.csv')